
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 27 17:32:48 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 16;
  public static final int INCREMENT = 31;
  public static final int CHAR = 48;
  public static final int CONST = 7;
  public static final int ASSIGNMENT = 30;
  public static final int GREATEROREQUAL = 24;
  public static final int SLASH = 19;
  public static final int LEFTSQUAREBRACKET = 39;
  public static final int NOTEQUAL = 23;
  public static final int GREATER = 26;
  public static final int CONTINUE = 15;
  public static final int MINUS = 44;
  public static final int LESS = 27;
  public static final int DECREMENT = 32;
  public static final int STAR = 18;
  public static final int STATIC = 17;
  public static final int RIGHTCURLYBRACKET = 42;
  public static final int SEMICOLON = 33;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int BOOL = 47;
  public static final int COMMA = 35;
  public static final int CLASS = 4;
  public static final int LESSOREQUAL = 25;
  public static final int NUM = 46;
  public static final int PLUS = 43;
  public static final int IF = 5;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 22;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PERCENT = 20;
  public static final int RIGHTPARENTHESIS = 38;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int ARROW = 21;
  public static final int COLON = 34;
  public static final int ELSE = 6;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int LEFTPARENTHESIS = 37;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int LEFTCURLYBRACKET = 41;
  public static final int RIGHTSQUAREBRACKET = 40;
  public static final int PRINT = 10;
}

